server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/