spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka