#spring:
#  application:
#    name: customer-service
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
server:
  port: 8081

spring:
  application:
    name: CUSTOMER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      root: INFO
      org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost